# 
# GitHub Actions workflow.
#
# Deploys RabbitMQ and MongoDB database.
#

name: Deploy infrastructure

on:
  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 
      # Deploys MongoDB.
      #
      - name: Deploy MongoDB
        run: kubectl apply -f ./scripts/cd/mongodb.yaml

      # 
      # Deploys RabbitMQ.
      #
      - name: Deploy Rabbit
        run: kubectl apply -f ./scripts/cd/rabbit.yaml
